name: build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build (linux/amd64, linux/arm64)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [ '1.25.x' ]
        arch: [ amd64, arm64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build server and CLI
        env:
          GOOS: linux
          GOARCH: ${{ matrix.arch }}
        run: |
          go mod download
          go build ./...

      - name: Build icecluster binary
        env:
          GOOS: linux
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -o dist/icecluster-${{ matrix.arch }} ./cmd/icecluster

      - name: Build icectl binary
        env:
          GOOS: linux
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -o dist/icectl-${{ matrix.arch }} ./cmd/icectl

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: icecluster-${{ matrix.arch }}
          path: |
            dist/icecluster-${{ matrix.arch }}
            dist/icectl-${{ matrix.arch }}
